In [1]:
#import imp libraries

import cv2
import numpy as np

In [2]:
thres = 0.45  # Threshold to detect object
nms_threshold = 0.2

In [3]:
# Initialize video capture
cap = cv2.VideoCapture(1)  # Change the index to 0 if it's the first camera
cap.set(3, 1280)  # Set width
cap.set(4, 720)   # Set height
cap.set(10, 150)  # Set brightness

False

In [4]:
#load the dataset
classnames = []
classfile = r"C:\Users\91738\Desktop\VS code all files\Open cv project\coco.names"

In [5]:
# Read class names from file
with open(classfile, 'rt') as f:
    classnames = f.read().rstrip('\n').split('\n')

print(classnames)

configpath = r"C:\Users\91738\Desktop\VS code all files\Open cv project\ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt"
weightspath = r"C:\Users\91738\Desktop\VS code all files\Open cv project\frozen_inference_graph.pb"

['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'street sign', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'hat', 'backpack', 'umbrella', 'shoe', 'eye glasses', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'plate', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'mirror', 'dining table', 'window', 'desk', 'toilet', 'door', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'blender', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush', 'hair brush']


In [6]:
# Load the pre-trained model
net = cv2.dnn_DetectionModel(weightspath, configpath)
net.setInputSize(320, 320)
net.setInputScale(1.0 / 127.5)
net.setInputMean((127.5, 127.5, 127.5))
net.setInputSwapRB(True)

< cv2.dnn.Model 0000020011036690>

In [7]:

while True:
    # Capture frame-by-frame
    success, img = cap.read()
    if not success:
        break

    # Detect objects
    classIds, confs, bbox = net.detect(img, confThreshold=0.5)
    print(classIds, bbox)

    if len(classIds) != 0:
        for classId, confidence, box in zip(classIds.flatten(), confs.flatten(), bbox):
            # Draw bounding box and label
            cv2.rectangle(img, box, color=(0, 0, 255), thickness=2)
            cv2.putText(img, classnames[classId-1].upper(), (box[0] + 20, box[1] + 40),
                        cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2)

    # Display the resulting frame
    cv2.imshow('Output', img)

    # Exit if the 'q' key is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

[ 1 82] [[442 204 583 516]
 [922 431 332 285]]
[1] [[443 202 578 517]]
[1] [[445 202 576 517]]
[1] [[445 202 576 517]]
[ 1 85] [[445 201 577 518]
 [242 433  73  44]]
[ 1 85] [[445 201 577 518]
 [242 433  73  44]]
[1] [[447 200 574 519]]
[ 1 85] [[449 201 567 519]
 [241 434  74  44]]
[ 1 85] [[449 201 567 519]
 [241 434  74  44]]
[ 1 85] [[446 202 575 518]
 [241 434  75  43]]
[ 1 85] [[446 202 575 518]
 [241 434  75  43]]
[ 1 85] [[445 203 575 517]
 [245 434  71  42]]
[ 1 85] [[445 203 575 517]
 [245 434  71  42]]
[1] [[446 204 572 515]]
[ 1 82] [[442 202 580 518]
 [922 434 338 280]]
[ 1 82] [[442 202 580 518]
 [922 434 338 280]]
[1] [[448 202 569 518]]
[1] [[448 202 569 518]]
[ 1 85] [[444 201 576 519]
 [245 432  72  46]]
[ 1 85] [[444 201 576 519]
 [245 432  72  46]]
[ 1 85] [[441 204 577 515]
 [243 434  73  44]]
[ 1 85] [[449 202 568 517]
 [245 431  71  46]]
[ 1 85] [[449 202 568 517]
 [245 431  71  46]]
[1] [[448 204 569 515]]
[1] [[448 204 569 515]]
[ 1 85] [[447 204 573 515]
 [244

In [8]:
# Release the video capture object and close all windows
cap.release()
cv2.destroyAllWindows()